# CBCA Book of the Year — 2018–2026 (출처: cbca.org.au awards-archive PDF/페이지, Books+Publishing, Readings 기사)
# (year, category, result, title, author)
CBCA = [
 # 2026 shortlist (winners not yet announced at time of build)
 (2026,'Younger Readers','Shortlist','Run','Sarah Armstrong'),
 (2026,'Younger Readers','Shortlist','Something Terrible: Tim Tie-Your-Shoelaces','Sally Barton'),
 (2026,'Younger Readers','Shortlist','Little Bones','Sandy Bigna'),
 (2026,'Younger Readers','Shortlist','Spirit of the Crocodile',"Aaron Fa'aoso & Michelle Scott Tucker"),
 (2026,'Younger Readers','Shortlist','The Paperbark Tree Committee','Karys McEwen'),
 (2026,'Younger Readers','Shortlist','Inked','Karen Wasson'),
 (2026,'Early Childhood','Shortlist','The Thing About Christmas','Jo Dabrowski'),
 (2026,'Early Childhood','Shortlist','Derek','Anne Donaldson'),
 (2026,'Early Childhood','Shortlist','Frogs Are Our Friends',"Toni D'Alia & Madeline White"),
 (2026,'Early Childhood','Shortlist','My Nonno Loves','Adelle Frittitta'),
 (2026,'Early Childhood','Shortlist','The Colours of Home','Sally Soweol Han'),
 (2026,'Early Childhood','Shortlist',"The Emperor's Egg",'Rae Tan'),
 (2026,'Picture Book','Shortlist','Bob and Dob','Sean E Avery'),
 (2026,'Picture Book','Shortlist','Tiwi in Paris','Glen Farmer Illortaminni'),
 (2026,'Picture Book','Shortlist','Dear Broccoli','Cate James'),
 (2026,'Picture Book','Shortlist','Dawn','Marc Martin'),
 (2026,'Picture Book','Shortlist',"The Frog's First Song",'Jason Phu'),
 (2026,'Picture Book','Shortlist','Once I was a Giant','Zeno Sworder'),
 (2026,'Eve Pownall','Shortlist',"There's a Prawn in Parliament House",'Annabel Crabb'),
 (2026,'Eve Pownall','Shortlist',"A Loo of One's Own",'Eleri Harris'),
 (2026,'Eve Pownall','Shortlist','Peculiar Parents','Stephanie Owen Reeder'),
 (2026,'Eve Pownall','Shortlist','The Thylacine and the Time Machine','Renée Treml'),
 (2026,'Eve Pownall','Shortlist','Caution! This Book Contains Deadly Reptiles','Corey Tutt & Ben Williams'),
 (2026,'Eve Pownall','Shortlist','Ningaloo','Tim Winton'),
 # 2025
 (2025,'Younger Readers','Winner','Laughter is the Best Ending','Maryam Master'),
 (2025,'Younger Readers','Honour','Aggie Flea Steals the Show','Tania Ingram'),
 (2025,'Younger Readers','Honour','Fluff: Mess Up!','Matt Stanton'),
 (2025,'Younger Readers','Shortlist','To and Fro','Anton Clifford-Motopi'),
 (2025,'Younger Readers','Shortlist','Tigg and the Bandicoot Bushranger','Jackie French'),
 (2025,'Younger Readers','Shortlist','Saskia Spark-Lee: Fundraiser Fail','Rebecka Sharpe Shelberg'),
 (2025,'Early Childhood','Winner','The Wobbly Bike','Darren McCallum'),
 (2025,'Early Childhood','Honour','How to Move a Zoo','Kate Simpson'),
 (2025,'Early Childhood','Honour','One Little Dung Beetle','Rhiân Williams'),
 (2025,'Early Childhood','Shortlist',"Don't Worry, Felix",'Yohann Devezy & Katharine Alice'),
 (2025,'Early Childhood','Shortlist','Spiro','Anna McGregor'),
 (2025,'Early Childhood','Shortlist','Everything You Ever Wanted to Know About the Tooth Fairy','Briony Stewart'),
 (2025,'Picture Book','Winner','The Truck Cat','Deborah Frenkel'),
 (2025,'Picture Book','Honour','Afloat','Kirli Saunders'),
 (2025,'Picture Book','Honour','These Long-Loved Things','Josh Pyke'),
 (2025,'Picture Book','Shortlist','The Garden of Broken Things','Freya Blackwood'),
 (2025,'Picture Book','Shortlist','A Leaf Called Greaf','Kelly Canby'),
 (2025,'Picture Book','Shortlist','We Live in a Bus','Dave Petzold'),
 (2025,'Eve Pownall','Winner','Always Was, Always Will Be','Aunty Fay Muir & Sue Lawson'),
 (2025,'Eve Pownall','Honour','Making the Shrine','Laura J Carroll'),
 (2025,'Eve Pownall','Honour','South With the Seabirds','Jess McGeachin'),
 (2025,'Eve Pownall','Shortlist','I am a Magpie, I am a Currawong','Bridget Farmer'),
 (2025,'Eve Pownall','Shortlist',"Flora: Australia's Most Curious Plants",'Tania McCartney'),
 (2025,'Eve Pownall','Shortlist','Design & Building on Country','Alison Page & Paul Memmott'),
 # 2024
 (2024,'Younger Readers','Winner','Scar Town','Tristan Bancks'),
 (2024,'Younger Readers','Honour','Huda Was Here','H Hayek'),
 (2024,'Younger Readers','Honour','Real Pigeons: Flap Out','Andrew McDonald'),
 (2024,'Younger Readers','Shortlist','The Sideways Orbit of Evie Hart','Samera Kamaleddine'),
 (2024,'Younger Readers','Shortlist','Being Jimmy Baxter','Fiona Lloyd'),
 (2024,'Younger Readers','Shortlist','Scout and the Rescue Dogs','Dianne Wolfer'),
 (2024,'Early Childhood','Winner','Gymnastica Fantastica!','Briony Stewart'),
 (2024,'Early Childhood','Honour','Grace and Mr Milligan','Caz Goodwin'),
 (2024,'Early Childhood','Honour','Bear and Duck Are Friends','Sue deGennaro'),
 (2024,'Early Childhood','Shortlist','One Little Duck','Katrina Germein'),
 (2024,'Early Childhood','Shortlist','Can You Teach a Fish to Climb a Tree?','Jane Godwin'),
 (2024,'Early Childhood','Shortlist','The Concrete Garden','Bob Graham'),
 (2024,'Picture Book','Winner','Timeless','Kelly Canby'),
 (2024,'Picture Book','Honour','Paper-flower Girl','Margrete Lamond'),
 (2024,'Picture Book','Honour','That Bird Has Arms','Kate Temple & Jol Temple'),
 (2024,'Picture Book','Shortlist','If I Was a Horse','Sophie Blackall'),
 (2024,'Picture Book','Shortlist','Every Night at Midnight','Peter Cheong'),
 (2024,'Picture Book','Shortlist','Bowerbird Blues','Aura Parker'),
 (2024,'Eve Pownall','Winner','Country Town','Isolde Martyn & Robyn Ridgeway'),
 (2024,'Eve Pownall','Honour','Australia: Country of Colour','Jess Racklyeft'),
 (2024,'Eve Pownall','Honour','Our Country: Where History Happened','Mark Greenwood'),
 (2024,'Eve Pownall','Shortlist','Eww Gross: Foul Facts and Putrid Pictures','Dan Marshall'),
 (2024,'Eve Pownall','Shortlist','This Book Thinks Ya Deadly!','Corey Tutt'),
 (2024,'Eve Pownall','Shortlist','Tamarra','Violet Wadrill, Topsy Dodd Ngarnjal & Leah Leaman'),
 # 2023
 (2023,'Younger Readers','Winner','Runt','Craig Silvey'),
 (2023,'Younger Readers','Honour','Evie and Rhino','Neridah McMullin'),
 (2023,'Younger Readers','Honour',"The Raven's Song",'Zana Fraillon & Bren MacDibble'),
 (2023,'Early Childhood','Winner','Where the Lyrebird Lives','Vikki Conley'),
 (2023,'Early Childhood','Honour','Bev and Kev','Katrina Germein'),
 (2023,'Early Childhood','Honour','Snap!','Anna Walker'),
 (2023,'Picture Book','Winner','My Strange Shrinking Parents','Zeno Sworder'),
 (2023,'Picture Book','Honour','Dirt by Sea','Michael Wagner'),
 (2023,'Picture Book','Honour','Paradise Sands','Levi Pinfold'),
 (2023,'Eve Pownall','Winner','DEEP: Delve into Hidden Worlds','Jess McGeachin'),
 (2023,'Eve Pownall','Honour','Come Together','Isaiah Firebrace'),
 (2023,'Eve Pownall','Honour','Wild Australian Life','Leonard Cronin'),
 # 2022
 (2022,'Younger Readers','Winner','A Glasshouse of Stars','Shirley Marr'),
 (2022,'Younger Readers','Honour','Dragon Skin','Karen Foxlee'),
 (2022,'Younger Readers','Honour','Rabbit, Soldier, Angel, Thief','Katrina Nannestad'),
 (2022,'Early Childhood','Winner','Jetty Jumping','Andrea Rowe'),
 (2022,'Early Childhood','Honour','Walk of the Whales','Nick Bland'),
 (2022,'Early Childhood','Honour',"Amira's Suitcase",'Vikki Conley'),
 (2022,'Picture Book','Winner','Iceberg','Claire Saxby'),
 (2022,'Picture Book','Honour','Stellarphant','James Foley'),
 (2022,'Picture Book','Honour','Just One Bee','Margrete Lamond & Anthony Bertini'),
 (2022,'Eve Pownall','Honour','The Illustrated Encyclopaedia of Peculiar Pairs in Nature','Sami Bayly'),
 (2022,'Eve Pownall','Honour','Heroes, Rebels and Innovators','Karen Wyld'),
 # 2021
 (2021,'Younger Readers','Winner',"Aster's Good, Right Things",'Kate Gordon'),
 (2021,'Younger Readers','Honour','The Stolen Prince of Cloudburst','Jaclyn Moriarty'),
 (2021,'Younger Readers','Honour','Worse Things','Sally Murphy'),
 (2021,'Early Childhood','Winner','No! Never!','Libby Hathorn & Lisa Hathorn-Jarman'),
 (2021,'Early Childhood','Honour','Anemone is Not the Enemy','Anna McGregor'),
 (2021,'Early Childhood','Honour','We Love You, Magoo','Briony Stewart'),
 (2021,'Picture Book','Winner','How to Make a Bird','Matt Ottley & Meg McKinlay'),
 (2021,'Picture Book','Honour','Not Cute','Philip Bunting'),
 (2021,'Picture Book','Honour','Your Birthday Was the Best!','Felicita Sala & Maggie Hutchings'),
 (2021,'Eve Pownall','Winner','Dry to Dry: The Seasons of Kakadu','Pamela Freeman'),
 (2021,'Eve Pownall','Honour','The Illustrated Encyclopaedia of Dangerous Animals','Sami Bayly'),
 (2021,'Eve Pownall','Honour','Strangers on Country','David Hartley & Kirsty Murray'),
 # 2020
 (2020,'Younger Readers','Winner','The Little Wave','Pip Harry'),
 (2020,'Younger Readers','Honour','The Glimme','Emily Rodda'),
 (2020,'Younger Readers','Honour','The Secrets of Magnolia Moon','Edwina Wyatt'),
 (2020,'Early Childhood','Winner','My Friend Fred','Frances Watts'),
 (2020,'Early Childhood','Honour','When Billy Was a Dog','Kirsty Murray'),
 (2020,'Early Childhood','Honour','Goodbye House, Hello House','Margaret Wild'),
 (2020,'Picture Book','Winner','I Need a Parrot','Chris McKimmie'),
 (2020,'Picture Book','Honour','Nop','Caroline Magerl'),
 (2020,'Picture Book','Honour','Three','Stephen Michael King'),
 (2020,'Eve Pownall','Winner','Young Dark Emu: A Truer History','Bruce Pascoe'),
 (2020,'Eve Pownall','Honour','The Illustrated Encyclopaedia of Ugly Animals','Sami Bayly'),
 (2020,'Eve Pownall','Honour','Willam: A Birrarung Story','Aunty Joy Murphy & Andrew Kelly'),
 # 2019
 (2019,'Younger Readers','Winner','His Name Was Walter','Emily Rodda'),
 (2019,'Younger Readers','Honour','Black Cockatoo','Carl Merrison & Hakea Hustler'),
 (2019,'Younger Readers','Honour','The Peacock Detectives','Carly Nugent'),
 (2019,'Early Childhood','Winner',"Tricky's Bad Day",'Alison Lester'),
 (2019,'Early Childhood','Honour','Heads and Tails: Insects','John Canty'),
 (2019,'Early Childhood','Honour','Here Comes Stinkbug!','Tohby Riddle'),
 (2019,'Picture Book','Winner','Cicada','Shaun Tan'),
 (2019,'Picture Book','Honour','The All New Must Have Orange 430','Michael Speechley'),
 (2019,'Picture Book','Honour','Chalk Boy','Mandy Ord'),
 (2019,'Eve Pownall','Winner','Sorry Day','Coral Vass'),
 (2019,'Eve Pownall','Honour','The Happiness Box','Mark Greenwood'),
 # 2018
 (2018,'Younger Readers','Winner','How to Bee','Bren MacDibble'),
 (2018,'Younger Readers','Honour','Henrietta and the Perfect Night','Martine Murray'),
 (2018,'Younger Readers','Honour','Marsh and Me','Martine Murray'),
 (2018,'Early Childhood','Winner','Rodney Loses It','Michael Gerard Bauer'),
 (2018,'Early Childhood','Honour','The Very Noisy Baby','Alison Lester'),
 (2018,'Early Childhood','Honour',"Hark, It's Me Ruby Lee!",'Lisa Shanahan'),
 (2018,'Picture Book','Winner','A Walk in the Bush','Gwyn Perkins'),
 (2018,'Picture Book','Honour','The Great Rabbit Chase','Freya Blackwood'),
 (2018,'Picture Book','Honour','Mopoke','Philip Bunting'),
 (2018,'Eve Pownall','Winner','Do Not Lick This Book','Idan Ben-Barak'),
 (2018,'Eve Pownall','Honour','Left & Right','Lorna Hendry'),
 (2018,'Eve Pownall','Honour','Koala','Claire Saxby'),
]
